{{ if not .Values.db.default }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-mongodb
  labels:
    name: {{.Release.Name}}-mongodb
spec:
  selector:
    matchLabels:
      name: {{.Release.Name}}-mongodb
      instance: {{.Release.Name}}-mongodb-node
  template:
    metadata:
      labels:
        name: {{.Release.Name}}-mongodb
        instance: {{.Release.Name}}-mongodb-node
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
          - name: db
            containerPort: 27017
            protocol: TCP
        volumeMounts:
        - name: {{.Release.Name}}-db-pv
          mountPath: /data/db
      volumes:
      - name: {{.Release.Name}}-db-pv
        persistentVolumeClaim:
          claimName: {{.Release.Name}}-db-pvc
{{ end }}

