apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-modules-pvc
spec:
  storageClassName: {{.Values.modules.storageClassName}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.modules.size}}