{{- $secret := (lookup "v1" "Secret" .Release.Namespace "amps-secret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque

# 2. If the secret exists, write it back
{{ if $secret -}}
data:
  cookie: {{ $secret.data.cookie }}
  keybase: {{ $secret.data.keybase }}
{{ else -}}
stringData:
  cookie: {{ randAlphaNum 32 | b64enc | quote }}
  keybase: {{ randAlphaNum 64 | b64enc | quote }}
{{ end }}
