apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svc-headless
  labels:
    name: {{.Release.Name}}
    instance: {{.Release.Name}}-svc-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4369
      targetPort: epmd
      protocol: TCP
      name: epmd
  selector:
    name: {{.Release.Name}}
    instance: {{.Release.Name}}-node