apiVersion: v1
kind: PersistentVolume
metadata:
  name: amps-temp-pv
spec:
  capacity:
    storage: {{.Values.tempSize}}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath: 
    path: /amps/data/tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{.Values.nodeHost}}
