apiVersion: v1
kind: Service
metadata:
  name: amps-svc-headless
  labels:
    name: amps
    instance: amps-svc-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4369
      targetPort: epmd
      protocol: TCP
      name: epmd
  selector:
    name: amps
    instance: amps-node