apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amps-temp-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.tempSize}}