apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-mongo
  labels:
    name: {{.Release.Name}}-mongo
spec:
  selector:
    matchLabels:
      name: {{.Release.Name}}-mongo
      instance: {{.Release.Name}}-mongo-node
  template:
    metadata:
      labels:
        name: {{.Release.Name}}-mongo
        instance: {{.Release.Name}}-mongo-node
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
          - name: db
            containerPort: 27017
            protocol: TCP