apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}
  labels:
    name: {{.Release.Name}}
    instance: {{.Release.Name}}-cluster
spec:
  replicas: {{.Values.replicas}}
  serviceName: {{.Release.Name}}-svc-headless
  selector:
    matchLabels:
      name: {{.Release.Name}}
      instance: {{.Release.Name}}-node
  template:
    metadata:
      labels:
        name: {{.Release.Name}}
        instance: {{.Release.Name}}-node
    spec:
      containers:
      - name: {{.Release.Name}}
        image: ampsv2:latest
        imagePullPolicy: IfNotPresent
        env:
        {{- range $key, $val := .Values.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        - name: RELEASE_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: AMPS_OPENSEARCH_ADDR
          value: https://opensearch-cluster-master:9200
        - name: AMPS_VAULT_ADDR
          value: http://{{.Release.Name}}-vault:8200
        - name: AMPS_MONGO_ADDR
          value: mongodb://{{.Release.Name}}-mongo:27017/{{.Release.Name}}
        - name: AMPS_NATS_HOST
          value: {{.Release.Name}}-nats
        - name: AMPS_NATS_PORT
          value: "4222"
        - name: DATAPIO_SERVICE_NAME
          value: {{.Release.Name}}-svc-headless
        - name: DATAPIO_APP_NAME
          value: {{.Release.Name}}
        # - name: RELEASE_COOKIE
        #   value: IDFRSSJFXFMWMBATZTZP
        # volumeMounts:
        # - name: {{.Release.Name}}-temp-pv-storage
        #   mountPath: {{.Values.tempMount}}
        # - name: {{.Release.Name}}-modules-pv-storage
        #   mountPath: {{.Values.moduleMount}}
        ports:
          - name: epmd
            containerPort: 4369
            protocol: TCP
      initContainers:
      - name: init-nats
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup {{.Release.Name}}-nats.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{.Release.Name}}-nats; sleep 2; done"]
      - name: init-vault
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup {{.Release.Name}}-vault.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{.Release.Name}}-vault; sleep 2; done"]
      - name: init-db
        image: curlimages/curl:latest
        command: ['sh', '-c', "until nslookup {{.Release.Name}}-mongo.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for {{.Release.Name}}-mongodb; sleep 2; done"]
      # volumes:
      # - name: {{.Release.Name}}-temp-pv-storage
      #   persistentVolumeClaim:
      #     claimName: {{.Release.Name}}-temp-pv-claim
      # - name: {{.Release.Name}}-modules-pv-storage
      #   persistentVolumeClaim:
      #     claimName: {{.Release.Name}}-modules-pv-claim
      
      #  ports:
      #  - containerPort: 8080