{{ if not .Values.db.default }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-mongodb
spec:
  selector:
    name: {{.Release.Name}}-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
{{ end }}