apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-ui-lb
  labels:
    name: {{.Release.Name}}-ui-lb
    instance: {{.Release.Name}}-ui-load-balancer
spec:
  type: LoadBalancer
  ports: 
    - name: amps
      port: {{ .Values.ui.http_port }}
      targetPort: {{ .Values.ui.http_port }}
    - name: amps-ssl
      port: {{ .Values.ui.ssl.port }}
      targetPort: {{ .Values.ui.ssl.port }}
  selector:
    name: {{.Release.Name}}-ui
    instance: {{.Release.Name}}-ui-node
