{{ if not .Values.db.default }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-db-pvc
spec:
  storageClassName: {{ default .Values.defaultStorageClass .Values.db.storageClassName}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.db.size}}
{{ end }}
