apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-cfg-pvc
spec:
  {{ if .Values.cfg.storageClassName }}
  storageClassName: {{ .Values.cfg.storageClassName}}
  {{ else if .Values.defaultStorageClass }}
  storageClassName: {{ .Values.defaultStorageClass }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.cfg.size}}