apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-temp-pvc
spec:
  {{- template "helpers.getStorageClass" .}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.temp.size}}