apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-misc-pvc
spec:
  storageClassName: {{.Values.misc.storageClassName}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.misc.size}}