apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-cfg-pvc
spec:
  storageClassName: {{ default .Values.defaultStorageClass .Values.cfg.storageClassName}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.cfg.size}}