{{ if not .Values.db.default }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-db-pvc
spec:
  {{ if .Values.db.storageClassName }}
  storageClassName: {{ .Values.db.storageClassName }}
  {{ else if .Values.defaultStorageClass }}
  storageClassName: {{ .Values.defaultStorageClass }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.db.size}}
{{ end }}
