apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-temp-pvc
spec:
  {{ if .Values.temp.storageClassName }}
  storageClassName: {{ .Values.temp.storageClassName}}
  {{ else if .Values.defaultStorageClass }}
  storageClassName: {{ .Values.defaultStorageClass }}
  {{ end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.temp.size}}