apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-misc-pvc
spec:
  {{ if .Values.misc.storageClassName }}
  storageClassName: {{ .Values.misc.storageClassName}}
  {{ else if .Values.defaultStorageClass }}
  storageClassName: {{ .Values.defaultStorageClass }}
  {{ end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.misc.size}}