apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-modules-pvc
spec:
  {{ if .Values.modules.storageClassName }}
  storageClassName: {{ .Values.modules.storageClassName}}
  {{ else if .Values.defaultStorageClass }}
  storageClassName: {{ .Values.defaultStorageClass }}
  {{ end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.modules.size}}